### ISSUE TITLE
Color for active window is not quite correct.

### ISSUE THREAD

**Issue by yifeikong** [TaDaa/vimade#10]
<img width="1680" alt="screen shot 2019-01-26 at 8 12 18 am" src="https://user-images.githubusercontent.com/1035487/51779432-53dc1080-2142-11e9-9e65-73f4781aa1a9.png">

As you can see, the active window on the right side does not get correct colorschema, some of the text are still dimmed.

Tmux 2.8 + Vim 8.0 + Vimade master(updated a few minutes ago)

VimadeInfo is

```
{"version":"0.0.1","python":{"BACKGROUND":"dark","BASE_FG":[208,208,208],"BASE_FG_LAST":"252","BASE_BG_EXP":"233","BASE_HI":[[208,208,208],[18,18,18]],"COLORSCHEME":"\nmolokai","HI_FG":" ctermfg=","ORIGINAL_BACKGROUND":"dark","BASE_BG":[1
8,18,18],"COL_BUF_SIZE":30,"IS_NVIM":0,"TERM_BG":"#000000","ROW_BUF_SIZE":30,"BASE_BG_LAST":"233","NORMAL_ID":"86","TERMGUICOLORS":0,"BASE_FADE":"59","FADE_LEVEL":0.4,"TERM_FG":"#FFFFFF","IS_TERM":1,"IS_TMUX":1,"BASE_FG_EXP":"252","HI_BG"
:" ctermbg="},"other":{"background":"dark","normal_hi":["252","233"],"vimade_py_cmd":"py3","has_gui":0,"has_python":0,"vimade_timer":903,"has_gui_running":0,"syntax":"python","has_nvim":0,"normal_id":86,"vimade_running":1,"colorscheme":"\
nmolokai","vimade_loaded":1,"vimade_usecursorhold":0,"has_python3":1},"config":{"basebg":"","basefg":"","fadelevel":0.4,"rowbufsize":30,"colbufsize":30,"normalid":86,"checkinterval":32}}
```

**Comment by TaDaa** [comment]
Looks like vimade got out of sync on bufleave, will try to reproduce later.   Is that nerd tree?

**Comment by yifeikong** [comment]
Yes, the left panel is nerdtree

**Comment by TaDaa** [comment]
Think this should be resolved now -- not sure what triggered this, but found 2 possibilities:
- there is some type of bug in matchaddpos, the passed winid is sometimes ineffective for w/e reason (this was always the case in nvim, but I am seeing this behavior on certain versions of vim as well)
- There was a bug when tabbing between Vim and other windows, sometimes the Nerdtree fade would get applied to the wrong window.  I think this is fixed, but not 100% yet.

**Comment by yifeikong** [comment]
Thanks. The problem is fixed now
