### ISSUE TITLE
"ImportError: cannot import name signs"

### ISSUE THREAD

**Issue by zamazir** [TaDaa/vimade#13]
Thanks for the nice plugin! I had trouble getting it to work though after installing it via vundle. Upon starting vim I was greeted with tons of error messages which I traced down to the python error in the issue title:

```
Error detected while processing function vimade#CheckWindows:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zama/.vim/bundle/vimade/lib/vimade/bridge.py", line 2, in <module>
    from vimade import signs
  File "/home/zama/.vim/bundle/vimade/lib/vimade/signs.py", line 5, in <module>
    from vimade import fader as FADE
  File "/home/zama/.vim/bundle/vimade/lib/vimade/fader.py", line 11, in <module>
    from vimade import signs
ImportError: cannot import name signs
Error detected while processing function vimade#Init[3]..vimade#DetectTermColors:
```

Turns out there is a superfluous `import signs` statement in fader.py.

I fixed the bug just by removing that statement and will create a pull request.

vim: 8.1
python: 3.6.7

**Comment by zamazir** [comment]
#14

**Comment by TaDaa** [comment]
Thanks for the report and first PR! - Merged and reversed the removal (remove fader from signs.py - for enablesigns to work)
