### ISSUE TITLE
[feature request] add list of regex buffer filters to exclude fading on

### ISSUE THREAD

**Issue by sdothum** [TaDaa/vimade#15]
Some plugins open multiple windows eg yankring. Would be nice to be able to provide a regex expression to be able to exclude fading of associated buffer windows when any are in focus, and faded when not.

**Comment by TaDaa** [comment]
Nice idea -- would something like VimadeIgnore [expr] or VimadeExclude [expr] suit your needs? -- The list itself I think will be exposed through the config.

Not quite sure what [expr] will be yet -- seems like it to start it should at least support matching on filetype, buffer/file name.

**Comment by sdothum** [comment]
Hadn't thought about filetype but I could see some use for that. As for var naming, perhaps VimadeGroupBuf and VimadeGroupFt or VimadeGroup (with a list of tuples using 'f' and 'b' types) eg VimadeGroupBuf ['regex1', 'regex2',...] or VimadeGroup [['b','regex1'], ['b','regex2'],...]. 

I don't have any particular preference for var naming or how you define the specification -- whatever is easiest for you to implement and is consistent with your coding. But simple regex matching on ft and buffer/filename would be awesome.

**Comment by TaDaa** [comment]
Starting to work on this -- should have it out there some time this week

**Comment by TaDaa** [comment]
Sorry for the delay -- I think this should do what you are looking for.  I steered away from the config to try and keep the logic moreso just vimscript in a vimrc.

Added the following commands:
```VimadeBufDisable``` - remove and ignore fading for the current buffer
```VimadeBufEnable``` - re-enable fading for current buffer
```VimadeWinDisable``` - remove and ignore fading for the current window
```VimadeWinEnable``` - re-enable fading for current window

usage examples:
```au! BufWinEnter Dockerfile VimadeBufDisable``` - Disables fading for buffers loaded that are named Dockerfile

```au! FileType nerdtree VimadeBufDisable```  - Disables fading for buffers with the nerdtree filetype>

**Comment by sdothum** [comment]
Thank you! This works for the Yankring plugin that caught my attention with it's multiple windows.

Great work.

**Comment by hrqmonteiro** [comment]
> Sorry for the delay -- I think this should do what you are looking for. I steered away from the config to try and keep the logic moreso just vimscript in a vimrc.
> 
> Added the following commands:
> `VimadeBufDisable` - remove and ignore fading for the current buffer
> `VimadeBufEnable` - re-enable fading for current buffer
> `VimadeWinDisable` - remove and ignore fading for the current window
> `VimadeWinEnable` - re-enable fading for current window
> 
> usage examples:
> `au! BufWinEnter Dockerfile VimadeBufDisable` - Disables fading for buffers loaded that are named Dockerfile
> 
> `au! FileType nerdtree VimadeBufDisable` - Disables fading for buffers with the nerdtree filetype>

Tried using the `au! FileType nerdtree VimadeBufDisable`, and got this ton of errors when opening Nerdtree:

![2021-03-07_18-09](https://user-images.githubusercontent.com/17055027/110254970-3c51f180-7f70-11eb-8f64-ab9fa81edf9c.png)
