### ISSUE TITLE
Error detected while processing function vimade#FadeCurrentBuffer

### ISSUE THREAD

**Issue by lholden** [TaDaa/vimade#2]
With the plugin installed and using *gvim* only (seems to work fine from the terminal), I get "Error detected while processing function vimade#FadeCurrentBuffer with a bunch of spam about "W18: Invalid character group in name". This seems to continue on some level as I navigate around and etc.

I am on vim 8.1

Love the idea of the plugin. 

```
Error detected while processing function vimade#FadeCurrentBuffer:
line    1:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
```

**Comment by phodge** [comment]
FWIW I got the same result in neovim v0.3.1

**Comment by TaDaa** [comment]
Was able to reproduce the w18 error in nvim, I am thinking gvim also did not like the '#' symbol in the highlight name, so it might be solved there as well.   Let me know if you are still seeing the error.

**Comment by lholden** [comment]
Just pulled down the latest release and it seems to be fixed for me now!
