### ISSUE TITLE
Vimade not loading - gnome-terminal

### ISSUE THREAD

**Issue by TaDaa** [TaDaa/vimade#22]
NVIM v0.4.0-762-g9420a2127 (AppImage), gnome-terminal

After having installed vimade with Vim-Plug: `Plug 'TaDaa/vimade'`, it looks like vimade hasn't been added correctly, command `VimadeEnable` is not recognized (same for others commands). Any ideas?

_Originally posted by @Leeshe in https://github.com/TaDaa/vimade/issues/1#issuecomment-503037071_

**Comment by TaDaa** [comment]
@Leeshe 
Can you check your ```:messages``` command in nvim.  Any errors there?

Also you sure the plugin installed correctly (used ```PlugInstall```)?  Also do you have python or python3 installed / enabled -- although those commands should show up regardless.

**Comment by Leeshe** [comment]
> Can you check your `:messages` command in nvim. Any errors there?

Nothing there.

> Also you sure the plugin installed correctly (used `PlugInstall`)? 

Yeah, I used `PlugInstall` and vimade is also present in the plugins directory.

>  Also do you have python or python3 installed / enabled -- although those commands should show up regardless.

Python3 is installed but it seems Neovim hasn't been built with Python:

```
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g 
-DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes 
-std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong 
-fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS 
-D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM 
-I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src 
-I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include 
-I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto 
-I/home/travis/build/neovim/bot-ci/build/neovim/build/include
```

**Comment by TaDaa** [comment]
What is your ```:CheckHealth```? -- should be a reference in there for whether or not python3/python was found

**Comment by Leeshe** [comment]
Here's the output:

```
## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=1).  This might be due to some previous error.
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Disabled (g:loaded_python3_provider=1).  This might be due to some previous error.
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/bin/python3 does not have the "neovim" module. :help |provider-python|
          python3.7 not found in search path or not executable.
          /usr/bin/python3.6 does not have the "neovim" module. :help |provider-python|
          python3.5 not found in search path or not executable.
          python3.4 not found in search path or not executable.
          python3.3 not found in search path or not executable.
          /usr/bin/python is Python 2.7 and cannot provide Python 3.
  - INFO: Executable: Not found
```

It seems this was the issue, after having installed Python support with `pip3 install neovim`, it works fine (at least, for the few tests I've done).

**Comment by TaDaa** [comment]
Ok great -- thanks for opening this, I'll look into adding an error during startup instead of quietly failing.
