### ISSUE TITLE
vimade swallows keystrokes on start

### ISSUE THREAD

**Issue by hupfdule** [TaDaa/vimade#24]
I noticed it when calling `git commit`.
Usually I start entering `i` and typing my commit message directly after calling `git commit`. This works well, even if vim didn't fully start up already. 
However when I have vimade installed it swallows my first keystrokes and the result is some garbage (depending on which keystrokes really made it into vim). I have a lot of other plugins active, but only vimade makes this problem.

**Comment by TaDaa** [comment]
This was likely being caused by detecttermcolors, which has been causing all kinds of other issues.  I've changed detecttermcolors so that its disabled by default (users will have to manually enable it at their own risk).  

Let me know if the issue is now fixed by default for you.

**Comment by hupfdule** [comment]
You are right. That fixes it!

Thank you very much (especially for the fast response!)
