### ISSUE TITLE
Background color is not dimmed

### ISSUE THREAD

**Issue by laggardkernel** [TaDaa/vimade#26]
During my test, it seems only syntax highlight is dimmed but not background color for text or the bg for folded line.

Environment: iTerm2 without tmux, Nvim 3.0.8. Colorscheme: vim-one light mode.

**Comment by TaDaa** [comment]
Will look into this.

From what I remember, folds can be tricky because  there is just one highlight group (Folded) and the highlighting can't really be controlled well to my knowledge - best way to make things look good is usually to clear the ctermbg/guibg for the Folded group.

**Comment by TaDaa** [comment]
This ended up being the case, basically the only highlight that works on Folds is the Folded (syntax matching doesn't work). 

I will add a flag for Vimade to override the colorscheme automatically.  We should be able to able to calculate a Folded highlight that  will work well both for the colorscheme and faded windows/buffers.

**Comment by TaDaa** [comment]
Folded is now supported for neovim and the other `built-in` highlight groups.  Basegroups are enabled by default, but you can also customize the groups that vimade fades using `g:vimade.basegroups`. 

Going to close this issue for now.   Let me know if its not working as expected or if there are other issues.
