### ISSUE TITLE
:helptags causes change to doc/tags file

### ISSUE THREAD

**Issue by mckellyln** [TaDaa/vimade#27]
running
:helptags <install-path ...>/.vim/bundle/vimade/doc
causes this change to doc/tags file:
+:VimadeOverrideFolded  vimade.txt      /*:VimadeOverrideFolded*
-g:vimade.overridefoldhighlight vimade.txt      /*g:vimade.overridefoldhighlight*
which then causes vimade to not be able to be updated by future git pulls.
Does anyone know why helptags would do this or how to avoid ?
thx for vimade

**Comment by TaDaa** [comment]
Should be all set after updating.  You may still have a conflict on doc/tags that needs resolution.

**Comment by mckellyln** [comment]
Thanks so much, works great!
