### ISSUE TITLE
Error when sourcing vimrc

### ISSUE THREAD

**Issue by tammersaleh** [TaDaa/vimade#28]
Something similar to #11 is still happening for me.  I have the following in my `.vimrc`:

``` vim
let g:vimade = {}
let g:vimade.enablesigns = 1
" https://github.com/TaDaa/vimade/issues/19
let g:vimade.usecursorhold=1
```

and when I reload the configuration, I get this error:

```
Error detected while processing function vimade#CheckWindows[1]..vimade#UpdateState:
E716: Key not present in Dictionary: normalid == "" || g:vimade.normalid == 0
```

I continue to get this error (but from `vimade#Tick`) every few seconds.

(note: I had to transcribe the error message by hand - apologies if there're typos)

**Comment by TaDaa** [comment]
Should be fixed in the latest commit, let me know if you have any issues

**Comment by tammersaleh** [comment]
Works a charm! 🙏
