### ISSUE TITLE
Error detected while processing function vimade#Init, undefined variable  g:vimade_py_cmd

### ISSUE THREAD

**Issue by rodrigore** [TaDaa/vimade#30]
Hi, today I run:
`:PlugUpdate`
and when I start neovim it show me a few error messages:
![image](https://user-images.githubusercontent.com/1557305/66764703-bd42b180-ee80-11e9-9d16-7caef7a3d62f.png)
![image](https://user-images.githubusercontent.com/1557305/66764712-c16ecf00-ee80-11e9-9b62-e037eedf8cd6.png)

**Comment by TaDaa** [comment]
Hi there -- mind checking the output of `checkhealth`.  Need to make sure python2 or python3 is being found.   

Also if you can print the output of VimadeInfo (if the command is not working due to the previous error), the output from `has('python')` and `has('python3')` would be helpful.  Thanks!

**Comment by rodrigore** [comment]
Hi, sorry for the delay. When I echo the has('python3') the result was 0, so I run:

`pip3 install --user neovim`

And the output was 1 which fix the  problem, Thank you!
