### ISSUE TITLE
Latest commit errors causes vimade#CheckWindows error

### ISSUE THREAD

**Issue by sdothum** [TaDaa/vimade#32]
Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
    Traceback (most recent call last):
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
      File "<string>", line 1, in <module>
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
      File "/home/shum/stow/vim/.vim/plugged/vimade/lib/vimade/bridge.py", line 1, in <module>
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
        from vimade import terminal
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
      File "/home/shum/stow/vim/.vim/plugged/vimade/lib/vimade/terminal.py", line 4, in <module>
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
        from vimade import global_state as GLOBALS
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
      File "/home/shum/stow/vim/.vim/plugged/vimade/lib/vimade/global_state.py", line 3, in <module>
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
        from vimade import colors
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
      File "/home/shum/stow/vim/.vim/plugged/vimade/lib/vimade/colors.py", line 3, in <module>
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
        from vimade import global_state as GLOBALS
    Error detected while processing function vimade#Init[15]..vimade#CheckWindows:
    line    3:
    ImportError: cannot import name global_state
    Error detected while processing function vimade#Tick:
    line   13:
    E605: Exception not caught: Vimade Error=1\nVim(python):ImportError: cannot import name global_state
    Error detected while processing function vimade#Tick:
    line   13:
    E605: Exception not caught: Vimade Error=2\nVim(python):ImportError: cannot import name global_state
    Error detected while processing function vimade#Tick:
    line   13:
    E605: Exception not caught: Vimade Error=0\nVim(python):ImportError: cannot import name global_state

Dist: Voidlinux
Vim: 8.1, Included patches: 1-2402

Reverting back to previous vimade branch e92851e does not error out.

**Comment by TaDaa** [comment]
will get this fixed tonight -- looks like Python2 might not be working on that latest one

**Comment by sdothum** [comment]
Thanks for the rapid fix! The plugin update resolved this issue with Vim.
