### ISSUE TITLE
Suggest to support the  lazy load officially.

### ISSUE THREAD

**Issue by kevinhwang91** [TaDaa/vimade#38]
When enabling vimade automatically, it will increase about 100ms during startup in my XPS 9370 i7  with ac mode. 
Here is my personal code to support the lazy load. 
```vim
Plug 'TaDaa/vimade', {'on': 'VimadeEnable'}
let g:vimade = {
            \'fadelevel': 0.6,
            \'checkinterval': 100,
            \'enablefocusfading': 1
            \}
autocmd BufNew * ++once if !exists('g:vimade_loaded') |
            \execute 'VimadeEnable' | endif
autocmd FocusLost * ++once if !exists('g:vimade_loaded') |
            \execute 'VimadeEnable' |
            \call vimade#FocusLost() | endif
```
To be honest, I think vimade is not necessary to initialize during startup.

**Comment by TaDaa** [comment]
Love it.  I only run vim with multiple buffers open simultaneously, but something like this would be a great improvement for anyone who may only edit within 1 window before `quitting` -- I'll get something out there to support this idea

**Comment by kevinhwang91** [comment]
Your habit impulses me to append the `WinNew` to `BufNew`.

**Comment by TaDaa** [comment]
This is now officially supported and added into the README:

lazy.nvim can be used if using Neovim.

For manual lazy loading like in the example above, use:

```vim
let g:vimade = {}
let g:vimade.lazy = 1

au WinEnter * ++once call vimade#Load()
```
