### ISSUE TITLE
[Feature request] Support to make neovim numhl of sign fade.

### ISSUE THREAD

**Issue by kevinhwang91** [TaDaa/vimade#39]
I saw some code in signs.py about linehl were commented.
```py
      # linehl adds high performance hit -- maybe add toggle for this
      # if 'linehl' in item:
        # linehl_id = vim.eval('hlID("'+item['linehl']+'")')
        # if linehl_id:
          # ids.append(linehl_id)
        # definition += ' linehl=vimade_' + linehl_id
```
and numhl of sign works after I added  below code. 
```py
      if 'numhl' in item:
        numhl_id = vim.eval('hlID("'+item['numhl']+'")')
        if numhl_id:
          ids.append(numhl_id)
        definition += ' numhl=vimade_' + numhl_id
```
But it must make sure that the option `checkinterval` of vimade greater than the option `updatetime` of neovim, otherwise, vim-gitgutter enabled `g:gitgutter_highlight_linenrs = 1` may works unexpected.

I don't know why, please support this feature with bug-free code.

**Comment by TaDaa** [comment]
Will get the issue you are talking about resolved, its been there in the back of my mind but I keep putting it off.

+1 for supporting numhl.  I want to say linehl should be supportable at this point on neovim as well given all the highlighting performance improvements it currently has over vim -- will look into re-enabling it.

**Comment by TaDaa** [comment]
linehl and numhl should now be supported with some perf improvements and logic for sign prioritization.  

Currently considering options to catch signs that might be triggered off of updatetime -- likely will update vimade to consult both signsretentionperiod and updatetime, which should handle most plugins without specific configurations.   Should have an update on this one in a day or 2.

**Comment by TaDaa** [comment]
Closing this out as this issue has been fixed.  Thanks for filing the report!
