### ISSUE TITLE
support dimming :terminal windows

### ISSUE THREAD

**Issue by tammersaleh** [TaDaa/vimade#46]
First off, thanks for vimade!  It really helps keep track of where I am when I'm using lots of splits, and it's great for pair programming.

I use `:terminal` windows heavily.  I'm not sure if this is possible, since `:terminal` doesn't use vim highlight groups, but it'd be awesome if we could dim those as well.

**Comment by TaDaa** [comment]
I believe there is a partial way to do this, but requires putting the terminal into normal mode before leaving it.  I use something similar to the remap below, which should work in both neovim and vim:

```
tnoremap <ESC> <C-\><C-N>
tnoremap <C-w> <C-\><C-N><C-w>
```

**Comment by tammersaleh** [comment]
Thanks @TaDaa - I'll give that a try

**Comment by TaDaa** [comment]
Closing this out as the remap above should work (neovim should be supported as well)
