### ISSUE TITLE
listchars were faded weirdly in some themes

### ISSUE THREAD

**Issue by kevinhwang91** [TaDaa/vimade#48]
Reproduce:
1. cat ~/mini.vim
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'TaDaa/vimade'
Plug 'joshdick/onedark.vim'
call plug#end()

set list
colorscheme onedark
```
2. `nvim -u ~/mini.vim +'split defer-multi.go' defer.go`
![image](https://user-images.githubusercontent.com/17562139/88703230-07123500-d13f-11ea-801c-875e311b5799.png)

The chars of the faded window were brighter than the unfaded one.

**Comment by gzbd** [comment]
Iceberg theme is also affected by this issue
![2020-10-30_20-28](https://user-images.githubusercontent.com/4434640/97749002-a18f6500-1aee-11eb-9ad2-899540f096af.png)

I would like to dim the listchars also.

I've tried to add `SpecialKey` and `NonText` to `basegroups` setting but it didn't work.

**Comment by ckangnz** [comment]
I can confirm that gruvbox is also affected. It's weird how it only affects certain SpecialKeys only?
<img width="1386" alt="image" src="https://github.com/TaDaa/vimade/assets/17423698/a9f66946-2906-4e8e-b597-74f3a5616f42">

<img width="1360" alt="image" src="https://github.com/TaDaa/vimade/assets/17423698/ced1f99f-6fdd-43f5-9c34-605fd2e1a5a0">
