### ISSUE TITLE
compatibility support for tilix

### ISSUE THREAD

**Issue by syedelec** [TaDaa/vimade#5]
Hi,

It seems that [tilix terminal](https://gnunn1.github.io/tilix-web/) is not supported. I'm using neovim with [Nord](https://github.com/arcticicestudio/nord-vim) colorscheme.

It works well using gvim.

```
$ tilix --version
Versions
	Tilix version: 1.8.9
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

```
$ echo $TERM
xterm-256color
```

Do you think the issue comes from my config ?
Thanks

**Comment by TaDaa** [comment]
I still have work to do on terminals, but I will take a look at this one as soon as I have a chance --- 

Some of had luck setting set termguicolors in the other terminal issue thread

**Comment by syedelec** [comment]
thanks, I just tried setting termguicolors but still no luck

**Comment by TaDaa** [comment]
-- pushed a fix where normalid couldn't be resolved on some terminals, let me know if it fixes this for you

**Comment by syedelec** [comment]
thanks !
it works well setting termguicolors.
Is it possible to use it without having to set termguicolors ?

**Comment by TaDaa** [comment]
Should work without termguicolors

Have it running without termguicolors on debian 9.6, nvim 0.3.4, tilix 1.6.4.  If its not working for you let me know  your versions, 'echo &t_Co' and 'echo g:vimade'

**Comment by syedelec** [comment]
Here is my full setup:
```
$ tilix --version
Versions
	Tilix version: 1.8.9
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

```
$ nvim --version
NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -[...]

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

- `echo &t_Co` gives `256`
- `echo g:vimade` gives `{ "basebg": '', "basefg": '', "fadelevel": 0.4, "rowbufsize": 30, "colbufsize": 30, "normalid": '', "checkinterval": 32 }`

My nvim config is located here : https://github.com/syedelec/.dotfiles/tree/master/nvim/.config/nvim

**Comment by TaDaa** [comment]
Just wanted to double check that you restarded nvim after doing PluginUpdate -- the normalid still isn't found , so thinking its still the older version of vimade -- 

if the normalid is still '' after restarting nvim, try going into the vimade directory and doing a git pull origin master

**Comment by syedelec** [comment]
I updated the vimade plugin and restarted nvim, now I have the output with a non-empty normalid :

`{'basebg': '', 'basefg': '', 'fadelevel': 0.4, 'rowbufsize': 30, 'colbufsize': 30, 'normalid': 53, 'checkinterval': 32}`

but I still don't see the fading if I unset termguicolors

**Comment by TaDaa** [comment]
Pushed a change that will probably resolve this!   I didn't get to test tilix again yet, but will later tonight.  

Copy paste from other threads:
There was a possibility that ctermfg/ctermbg does not get set (when it uses the terminal defaults). There isn't a 100% way of getting the terminal settings (and tmux n, but Vimade should at least try now and default to 0/248 if it can't.

I think for best results a colorscheme that specifies Normal colors needs to be used, or vimade needs to be configured using g:vimade.basebg and g:vimade.basefg. I'll update the readme, but I think it should autodetect for you on Ubuntu + Kitty (which prints the right codes -- Alacritty is another story)

**Comment by TaDaa** [comment]
Spoke too soon, almost though

**Comment by TaDaa** [comment]
Support should be better for you -- can also autodetect the terminal colors on tilix for vim 8.  Nvim is currently not supported for autodetect colors, but should default to white/black fades which should work pretty good regardless of the colorscheme.  

Planning to look more into neovim support for autodetection, but it requires hacking on the tty/pid (since neovim is actually not a tty:()

**Comment by TaDaa** [comment]
Let me know how it goes, I will close out this tomorrow night, but feel free to open it if you are still having issues
