### ISSUE TITLE
Neovim tree-sitter support...

### ISSUE THREAD

**Issue by bresilla** [TaDaa/vimade#52]
I know that NoeVim's tree-sitter highlight feature is still not out and will be out with upcoming realease of NeoVim (0.5), but would be cool if this plugin can support that, because the GRAND idea of TreeSitter is that - at the end of the day - all languages have some kind of AST thus can be made possible that all highlight groups of similar tree can be the same.

I have noticed this plugin is not able to detect those highlights from tree-sitter thus rendering all the buffer when not active without any colors.

I don't know the internals of this plugin (probably i should have checked a bit before making a feature-request), but TreeSitter in other hands makes some completely new highlight groups. For example Strings or Constants in Tree-Sitter are TSStrings or TSConstants and so on... and for all languages they are always the same.

**Comment by TaDaa** [comment]
Thanks @bresilla .  I'll have to look into this.  I assume you are using nvim-treesitter?  

It doesn't seem like treesitter ties into the current syntax ecosystem; this would not work with any plugins that are using  synID to determine highlights (e.g this also breaks vim-illuminate).   I'll have to do some more digging to see if there is a way to make synID work with treesitter.  If not maybe there is alternate another way to query the highlight groups.   I'll also try opening an issue with neovim or nvim-treesitter, just not sure exactly where the issue belongs yet.

**Comment by TaDaa** [comment]
This is very experimental as its leveraging undocumented nvim treesitter internals, but support can now be enabled by adding ```
 let g:vimade = {}
 let g:vimade.enabletreesitter=1
```

Still have some digging to do, but this seemed like the shortest path to support treesitter currently.  I'm thinking I may need to start providing a lua only option for neovim users, I need to figure out how to best support that though and when per window color schemes are landing.

**Comment by bresilla** [comment]
Amazing. I will try and give you feedback after some usage.
Thank you.

**Comment by TaDaa** [comment]
Closing this out as the issue was fixed and stable thus far
