### ISSUE TITLE
Enhancement (Vim): Fade line numbers by default

### ISSUE THREAD

**Issue by poetaman** [TaDaa/vimade#57]
Currently line numbers displayed to the left of window are not covered dimmed by default. It would be nice if that happens by default, or please provide a setting for Vim users (I guess ``g:vimade.basegroups`` could do that, but they are only for neovim?). Is there a big performance penalty?

**Comment by TaDaa** [comment]
Hi @reportaman  -- 
Unfortunately g:vimade.basegroups is neovim only and vim as far as I'm aware does not have an equivalent option to set winlocal highlights. 

For vim you can use ```VimadeOverrideLineNr``` or ```VimadeOverrideAll``` which will set some of the basegroups to use vimade_0, which should look better in most cases.

**Comment by TaDaa** [comment]
This is actually now possible for *Vim*as well.  The updates to this pllugin leverage the way **wincolor** works to do it, the only requirement is that users link the target highlight to `Normal` (`hi! default link LineNr Normal`).

**Comment by TaDaa** [comment]
This is now supported for vim as well:

You can use `let g:vimade.linkwincolor=['LineNr']` or add any other highlights into the list.  Vimade will link the list to Normal and then perform wincolor highlighting to fade them if needed.  The downside is that they are linked to Normal on the active window as well.

This is used in the Minimalist recipe to completely fade out low-value built-ins, which can be used like this:

```python
python << EOF
from vimade import vimade
from vimade.recipe.minimalist import Minimalist
vimade.setup(**Minimalist(animate = True))
EOF
```
