### ISSUE TITLE
Does not redraw and respect winwidth after executed command :source ~/.vimrc and :VimadeRedraw

### ISSUE THREAD

**Issue by hoango7604** [TaDaa/vimade#59]
Hello @TaDaa, I am stucking with this issue for a while and haven't found a proper solution. Whenever I ran command :source ~/.vimrc, all unfocused windows will no longer be faded any more, and I have to call :VimadeRedraw to trigger fading by hand.

![issue-redraw](https://media.giphy.com/media/NKXuxUynfX1SxZcxCq/giphy.gif)

So for a work around, I remap <leader>ss to :source ~/.vimrc<Bar>:VimadeRedraw<CR>. Things even get worse when I use [vim-maximizer](https://github.com/szw/vim-maximizer). When the window is being maximized and command :VimadeRedraw is executed, the minimized windows "stretch" a little although I expected it to keep the same.

![issue-maximizer](https://media.giphy.com/media/aSkK7EhNEt88pprCIx/giphy.gif)

Really hope you could help me out. Thank you.

**Comment by TaDaa** [comment]
I believe this should fix ```source ~/.vimrc```

On the resizing..it seems like when vimade switches windows behind the scenes,  vertical resize is triggering due to winwidth settings.  I've added a really hacky workaround and it seems to be better,  but let me know if you see any issues.

**Comment by hoango7604** [comment]
Sorry for being inactive for a long time, since I have read your comment but forgot to response. Your workaround worked perfectly without any modification. Thank you in advance!
