### ISSUE TITLE
lose color on other explorer?

### ISSUE THREAD

**Issue by v6cc** [TaDaa/vimade#60]
I tried `netrw , nerdtree` work ok

but 
[coc-explorer](https://github.com/weirongxu/coc-explorer)
[defx](https://github.com/Shougo/defx.nvim)

will lose highlight when not focus?

**Comment by TaDaa** [comment]
Hi there, I will take a look at this later today -- guessing that these explorers are no longer using syntax highlighting, will have to verify and see what is going on and if there are options.   Another option could be possible to disable Vimade on those buffers using an autocmd and  VimadeBufDisable or VimadeWinDisable.

**Comment by TaDaa** [comment]
These trees should now be fully supported on Neovim v0.8.0 or higher
