### ISSUE TITLE
Vim EndOfBuffer area is not fading

### ISSUE THREAD

**Issue by sriramkandukuri** [TaDaa/vimade#66]
Hi,

normal text area is fading as expected but EndOfBuffer area is not fading while moving to any other pane or window.

**Comment by TaDaa** [comment]
Hi there -- if you are using Neovim the latest update should fix this for you, `EndOfBuffer` is now added into g:vimade.basegroups.  

If you are using Vim you may want to consider overriding the `EndOfBuffer` highlight to match Normal ctermbg/guibg -- the command  `VimadeOverrideEndOfBuffer` will override the highlights for you.

**Comment by sriramkandukuri** [comment]
Yes I am using neovim mainly.

Is there a way to configure this plugin in lua.

**Comment by TaDaa** [comment]
Yes all plugin configs should be accessible through lua -- most have options in the `g:vimade` variable. 

Something like this should work fine:
`vim.g.vimade = vim.tbl_extend('force', vim.g.vimade, {["fadelevel"] = 0.2})`
