### ISSUE TITLE
Document installation / configuration with Lazy (AstroNvim)

### ISSUE THREAD

**Issue by jondkinney** [TaDaa/vimade#76]
If you're using Lazy to manage your plugins, this worked for me in AstroNvim, which uses Lazy.

```lua
---@type LazySpec
return {
  {
    "TaDaa/vimade",
    config = function()
      vim.g.vimade = {
        enabletreesitter = 1,
        fadelevel = 0.7,
        enablesigns = 1,
      }
    end,
  },
}
```

I haven't messed with the settings too much yet, but that should at least get you going.

**Comment by TaDaa** [comment]
Thanks for flagging!  The README has now been updated with lazy.nvim instructions... **Vimade** can now be configured using:

```
require('lazy').setup({spec = {'tadaa/vimade'}})
```

For the options in the config above you should just need:

```lua
return {
  {
    'TaDaa/vimade',
     opts={
       fadelevel=0.7
     }
  }
}
```
