### ISSUE TITLE
vimade.signsid may be incorrect for lewis6991/gitsigns.nvim?

### ISSUE THREAD

**Issue by jondkinney** [TaDaa/vimade#79]
I'm not sure if it's the signsid, but there seems to be a conflict between the [gitsigns](https://github.com/lewis6991/gitsigns.nvim?) and what vimade is substituting in. In the video I show it in the incorrect state, then edit the file via `:e` which restores the correct gitsigns, then navigating away and dimming the pane clobbers the signs.

https://github.com/user-attachments/assets/59aa40c4-0e78-49ac-90e4-e06959a3903f

**Comment by TaDaa** [comment]
This should be resolved with the latest changes.  Neovim now has a Lua only mode that should activate for everyone on 0.8 or higher
