### ISSUE TITLE
Invalid channel: 3

### ISSUE THREAD

**Issue by yriveiro** [TaDaa/vimade#8]
Some times when I close neovim I had this error:

```python
Error detected while processing function vimade#CheckWindows[6]..provider#python3#Call:
line   18:
Invalid channel: 3
```

OSX: mojave
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5

**Comment by TaDaa** [comment]
Thanks for the report, someone else mentioned this as well...I will see if I can address this today

**Comment by TaDaa** [comment]
Pushed a fix, but looks like its a problem with nvim, happens with with the plugin disabled, just a different python error occurs

**Comment by TaDaa** [comment]
Closing this for now, but feel free to reopen if you encounter this due to vimade again
