### ISSUE TITLE
Issue: Highlighted Vertical Separator 

### ISSUE THREAD

**Issue by zebra-f** [TaDaa/vimade#81]
I have this highlighted vertical separator:
![issuevimade](https://github.com/user-attachments/assets/9c6a53c6-abe7-4430-8c8f-12123e94c110)
Top `Shade`, bottom `vimade`.

I've tried a different theme, different tree but it's still there (it's only visible when the tree is opened). It's not present in `README.md` examples. 
Small thing but really distracting and bothering. 
I would like to use `vimade` as I like how it behaves when the same file is opened in two windows (both are highlighted). Also it looks like it's still maintained compared to Shade.

**Comment by TaDaa** [comment]
Thanks for reporting!  Just pushed an update that should address this. LMK if it fixes the issue for you

**Comment by zebra-f** [comment]
> Thanks for reporting! Just pushed an update that should address this. LMK if it fixes the issue for you

Works, but now the tree is monotone and it takes like a solid second for the tree to dim. 
![Screenshot_20241013_001349](https://github.com/user-attachments/assets/22f95288-ecdb-4566-b003-e422c6198422)

**Comment by TaDaa** [comment]
Doh hmm, have you tried `VimadeRedraw` to see if it fixes the highlights?  Also just wanted to make sure that you also restarted Neovim after updating this plugin (there is a lot of background caching that could potentially break how things are colored)?

If it's still not working I'll probably need an init.vim / vimrc that has the issue (the smaller the better, but happy to go through it either way).

This is what I see for reference:
<img width="680" alt="Screenshot 2024-10-12 185348" src="https://github.com/user-attachments/assets/a16c8bd3-9b26-460f-a89f-09418b2926b2">

**Comment by zebra-f** [comment]
Yes I restart nvim every time, `VimadeRedraw` doesn't work, also I have tried without tmux just in case.
Also when I change window from the tree it light everything up: 

https://github.com/user-attachments/assets/1629163e-10a6-4bb5-b7b4-3fdda977cf69

It doesn't happen with lighter or no theme plugin (not sure where this 'theme' was a part of kickstart):

https://github.com/user-attachments/assets/aedca7d4-e26f-457f-8226-490daf1b3599

This is my nvim setup:
https://github.com/zebra-f/nvim-config/blob/main/lua/custom/plugins/init.lua
there is also `init.lua` in the root, link points to the file where `vimade` is 'installed'. 
I can't locate these `init.vim / vimrc` files on my system (at least in Home dir).

**Comment by TaDaa** [comment]
Ah great that's super helpful! 

Can you remove all  `vimade` startup settings from your init.lua (you don't need any of that `vim.g.vimade` object); none of those config will actually affect you because you are in  `lua`-only mode.  Somehow overriding the base `vimade` object via lua is breaking the extension process.  I'll have to fix it when I get back from groceries.

`lua` only mode isn't documented for this plugin yet b/c it's not quite ready for full-release, but I've enabled this feature for users who don't have pynvim installed.  The lua version is preferrable, so  If you do end up installing pynvim, you can keep `vimade` in `lua` mode by using `let g:vimade.renderer='auto'`


`

**Comment by zebra-f** [comment]
> Can you remove all `vimade` startup settings from your init.lua (you don't need any of that `vim.g.vimade` object); ver few of those config will actually affect you because you are in `lua`-only mode.

Unfortunately leaving only: 
```lua
  {
    'TaDaa/vimade',
  }
```
doesn't solve the issue. 
I will look tomorrow for any changes. 
Btw. admirable dedication, but take your time I'm already feeling bad for causing problems and possibly wasting your time. 
Thank you and good luck.

**Comment by TaDaa** [comment]
Ha no worries! Appreciate the flagging the issue would love to fix it. I want to get this plugin re-released soon, so this is actually a big help!  If you have a chance,  try adding  `let g:vimade.renderer='auto'` to your config and maybe there will be colors again 🤞 ?  I'm guessing, but maybe you got moved into legacy or python mode 

If still not working after switching to 'auto' also include  output of `:VimadeInfo`

**Comment by zebra-f** [comment]
> try adding `let g:vimade.renderer='auto'` to your config and maybe there will be colors again 🤞 ?
 
It's working as expected!
This is my `init.lua`:
```lua
...
  -- {
  --   'TaDaa/vimade',
  --   config = function()
  --     require('vimade').setup({
  --       fadelevel = 0.9
  --     })
  --     vim.g.vimade.renderer = 'auto'
  --   end
  -- },
  {
    'TaDaa/vimade',
    config = function()
      vim.cmd [[
      if !exists('g:vimade')
        let g:vimade = {}
      endif
      let g:vimade.fadelevel = 0.6
      let g:vimade.renderer = 'auto'
    ]]
    end
  }
...
``` 
Commented doesn't work, bottom one was provided by Claude (LLM), it works without `let g:vimade = {}` so it suggested to add `if !exists...` line just in case. 
Thanks you again!

**Comment by TaDaa** [comment]
Great! glad `renderer='auto'` is working!  `auto` will be the new default soon (probably this week or next).  

----
For the other issue with empty config, I'm guessing that you have treesitter enabled? What's ends up happening is that with no config you end up getting put on `python-legacy`.  In all python modes `let g:vimade.enabletreesitter=1` needs to be set manually for treesitter highlights (`synID` returns 0 when syntax is disabled), although It probably makes sense for me to just default this to enabled so less configuration is required.

**Comment by zebra-f** [comment]
More bad news :( 
With the current setup there is a new Issue with `'lukas-reineke/indent-blankline.nvim'` 

https://github.com/user-attachments/assets/e985a39c-66f5-46b1-85b8-c7a61d88ea38

First example is `Shade`, it everything correctly, second `vimade` dims current indent line (?), but other lines get highlighted. 
I've tried to run `let g:vimade.renderer = 'auto'` manually if it needs to be set after `indent-blankline` but it doesn't help (not sure if it even makes sense).

**Comment by TaDaa** [comment]
can you send me the config you are using for `indent-blankline`?  I do notice its not playing well on some thing, but its not exactly the same issue that you are seeing (for me its not dimming the top and bottom scope text correctly ... could be related though)

Regarding `let g:vimade.renderer='auto'` -- doesn't need to be after, the earlier its there the better

**Comment by TaDaa** [comment]
That fix may improve things?

 If not just shoot me the config and will take a closer look -- I'll try to repro on my other system as well

**Comment by zebra-f** [comment]
> That fix may improve things?  

Everything works correctly now! Good job.

**Comment by TaDaa** [comment]
Ah sorry for the confusion, yeah you'll need the second config going forward until the release is finished.  pynvim is probably installed in one environment but not the other, so pynvim environment gets the gimped experience.

Thanks for flagging nvim-tree! I'll take a look later tonight

**Comment by TaDaa** [comment]
Support for this should be much better across the board (at least in Neovim 0.10+).  The issue here seems to be that these two tree plugins create circular highlights for many builtin highlights.  Primarily Normal and NormalNC are the most problematic ones.  

Neovim seems to handle this scenario inconsistently and either return some color along the path of the circular route and/or the many API functions return bad results (e.g. passing `link=false` into nvim_get_hl will still return a link... some of the other functions will just return the wrong color completely). 

Closest way that I seemed to be able to handle it seems to be manually determining how the link should have been resolved.  This is still slightly inaccurate in a couple of edge cases that Neovim isn't resolving correctly (Neovim will short the link in some scenarios passing through Normal/NormalNC when it can still be followed), but overall this should work well enough

**Comment by TaDaa** [comment]
Issue here should be fixed and `g:vimade.auto` is now the default behavior, so you shouldn't need to manually set this anymore!  The `setup` commands should all be working now as well & documentation is mostly updated.

Thank you for reporting!
