### ISSUE TITLE
Option to enable fading only for floating windows

### ISSUE THREAD

**Issue by darianmorat** [TaDaa/vimade#82]
As the title says, is there any option for this? The reason I want to get this working only for floating windows is that I want to better focus on windows like Telescope, so that I don't have all the overlap with the text behind.

I got this workaround for now... But I would like to know if there's a better option for it:
```lua
vim.api.nvim_create_autocmd({"WinEnter"}, {
   callback = function()
      local win_config = vim.api.nvim_win_get_config(0)
      if win_config.zindex then
         vim.cmd("VimadeEnable")
      else
         vim.cmd("VimadeDisable")
      end
   end
})
```

**Comment by TaDaa** [comment]
Yep!  Was planning this to address #44 as well, but you'll want the latest update so that named lists don't overwrite the entire config object.

The `only_behind_float_windows` is just an arbitrary name

```lua
require('vimade').setup({
  blocklist = {
    only_behind_float_windows = function (win, current)
      -- current can be nil
      if (win.win_config.relative == '') and (current and current.win_config.relative ~= '') then
        return false
      end
      return true
    end
  }
})
```

works in python as well:

```python
from vimade import vimade
def only_behind_float_windows (win, current):
  if (win.win_config['relative'] == '') and (current and current.win_config['relative'] != ''):
    return False
  return True

vimade.setup(blocklist = {
    'only_behind_float_windows': only_behind_float_windows,
})
```

**Comment by darianmorat** [comment]
Thank you, that's exactly what I was looking for
