### ISSUE TITLE
Split the same buffer does not change colors

### ISSUE THREAD

**Issue by voyeg3r** [TaDaa/vimade#84]
Inactive window does not change colors when we split the same buffer

**Comment by TaDaa** [comment]
buffer fading is the default mode.  

If you want window fading you need to enable it via n mode:



Vimscript::
```
let g:vimade={}
let g:vimade.ncmode='windows'
```

Lua
```
require('vimade').setup{ncmode='windows'}
```

Python
```
from vimade import vimade
vimade.setup(ncmode='windows')
```

**Comment by TaDaa** [comment]
Just wanted to update this thread as it gave me an idea for a new recipe.  The idea is to apply *window* and *buffer* fading but to separate degrees.  This way you can distinguish what is a same-split buffer (while it still looks faded) and what is completely separate.

It's called **Duo** and you can try it out using the following if interested:

lua:
```lua
local Duo = require('vimade.recipe.duo').Duo
require('vimade').setup(Duo{animate = true})
```
