### ISSUE TITLE
Blocklist for highlights

### ISSUE THREAD

**Issue by pynappo** [TaDaa/vimade#85]
I'd like to prevent some UI highlights from getting affected by vimade (mostly statusline ones, because I use `laststatus=3` in neovim and this plugin causes the single global statusline to flicker).

I didn't see a clear option for this in the docs, since `blocklist` works on a buf/win basis.

For example, in https://github.com/levouh/tint.nvim, i can block whole groups of highlights with:

```lua
require('tint').setup({
      highlight_ignore_patterns = {
        'WinSeparator',
        'Status.*',
        'Normal.*',
        'CursorLine',
        'Dropbar',
        'Color',
        'WinBar',
      },
})
```

something like:

```lua
blocklist = {
	default = {
		hl_name = {}, -- list of names
		hl_opts = function(hl_name)
			-- ...
			return true -- or false		
		end
	}
}
```

would probably make the most sense given this plugin's support for multiple languages

**Comment by TaDaa** [comment]
Thanks for flagging & happy to add this in a few @pynappo!

**Comment by TaDaa** [comment]
Added to the Lua path for Neovim only as `laststatus=3` was a good use-case.  It had to stay separate from blocklist due to intents (all the blocklist related functions are window based), so went with `disabled_highlights`...

The default is now set to the following:

```lua
vimade.setup({
   -- ...
  disabled_highlights = {
    default = {
      function(hi_name)
        -- see #85 prevent global statusline from flickering due to multiple windows impacting
        -- StatusLine highlight.
        return hi_name == 'StatusLine' and vim.go.laststatus == 3
      end
    },
     -- also accepts any highlight names (excluding Normal/NormalNC) . For example:
     -- 'LineNr',
     -- 'LineNrAbove',
     -- 'WinSeparator',
     -- 'etc'
  },
  -- ...
})
```


I can't think of a use-case it would be needed in the python logic atm, so I'll probably just leave it as lua-only until someone asks for it (the same approach can be implemented there as well if needed).

**Comment by TaDaa** [comment]
Ok lol, sorry changed my mind blocklist makes more sense as you had suggested:D

There were a few things irking me about how I added that last change:

- It was overkill requiring comparisons to be run on each highlight.  
- Each window might want its own set of blocked highlights
-  Also I think I miscaptured the problem with `laststatus=3`... The ownership shifts of the StatusLine when the window changes, which makes sense.   In this scenario, Vimade shouldn't fully disable the highlight, instead it should just prevent highlighting of the 'inactive' window that way `active` highlighting still works.

Here is the updated configuration, which I think fits better now:

```

require('vimade).setup({
   -- ...
  blocklist = {
    -- runs the default_matcher with this config
    -- any value that is a config goes to the
    -- default matcher
    --
    -- this is set to an empty object to enforce the default condition
    -- for legacy conditions
    default = {
      highlights = {
        function(win, active)
          -- see #85 prevent global statusline from flickering due to multiple windows impacting
          -- StatusLine. laststatus=3 also causes some misalignment on WinSeparator, if you see
          -- issues consider either also excluding 'WinSeparator' or tweaking the WinSeparator
          -- guibg until you find a value that looks good.
          -- permits StatusLine on the active window for active highlights
          if vim.go.laststatus == 3 and win.nc ~= active then
            -- alternatively return an array-like (e.g.  {'StatusLine', 'WinSeparator'}  )
            return 'StatusLine'
          end
        end,
        -- Also can specify names, example:
        -- 'WinSeparator',
      },
      buf_name = nil,
      -- terminal is temporarily disabled until proper fading is added
      buf_opts = {buftype = {'prompt', 'terminal'}},
      buf_vars = nil,
      win_opts = nil,
      win_vars = nil,
      win_type = true,
      win_config = {
        relative = true
      },
    },
  },
  -- ...
})

```

**Comment by TaDaa** [comment]
Pattern matching is now supported.  To use pattern matching just use a string but in the following format:

`'/^StatusLine.*/'`

If there are regex symbols, Vimade will identify the string as a pattern.  Just a note that exact names should be preferred when possible as they are just an O(1) lookup.  Patterns are O(N) once per tick and then O(1) aftewards (Vimade will cache the matches and then re-use them when possible).

I think long-term I'd like to properly support `laststatus=3`, but it needs some work... I think the goal should be that Vimade understands global highlights and when to transition them from active to active states (i.e. they don't ever go inactive unless the active window is inactive).  I plan to look into this further later in the week as it seems feasible.

**Comment by TaDaa** [comment]
So cool news active to active is basically already supported (just needs some finishing touches)

Statusline is kind of unique though, I'll likely include some type of combinable recipe or component that targets it at some point, but TBD on that.  

-----

I think everything is supported from my perspective for blocked highlights (and readme updated), so closing this issue.   Thanks for flagging @pynappo and feel free to reopen if anything ends up not working out for you.
