### ISSUE TITLE
Question: how to not fade rest windows when in a window with certain filetypes

### ISSUE THREAD

**Issue by toooonyy** [TaDaa/vimade#86]
First of all, thank you for this great plugin!

I’m trying to configure it so that certain windows don’t fade under specific conditions. So far, I’ve managed to use the `blocklist` option to prevent supplementary windows (e.g., `undotree` the right column or `nerdtree` the left column) from fading when I focus on the main window (like the `vimade.vim` window in the screenshot). This behavior is as desired. Additionally, I’ve used `link` rules to make supplementary windows not fade together when fcous on one of the supplementary windows, which works well.

However, I can’t get the reverse to work. Specifically, when I focus on supplementary windows like `nerdtree` or `undotree`, I’d like the main window to remain unfaded. This would be especially helpful when going through `undotree` so I can see how the code changes in real time.

![1](https://github.com/user-attachments/assets/89e81c2f-9097-4d8e-bc73-22a3f8b3c6b4)

You can see my current configuration in the screenshot. For reference, I’m using Vim 9.1. Reatly appreciated your guidance!

**Comment by TaDaa** [comment]
Cool setup:D

I think you can accomplish what you want to do with either link or blocklist.  I'd probably recommend blocklist in this scenario if possible because it's less complex internally:).

Does this get you close to what you are trying to do?  This will unfade everything when 'NERDTree' is focused -- for the `main` window part I'm guessing you may want some additional logic before returning `True`

```python
python3 << EOF 
from vimade import vimade
def block_when_nerdtree_opened(win, active):
  if active and 'NERDTree' in active.buf_vars:
    return True
  return False
vimade.setup(
  blocklist = {
    'block_when_nerdtree_opened': block_when_nerdtree_opened,
  }
)
EOF

```

**Comment by toooonyy** [comment]
> Cool setup:D
> 
> I think you can achieve the reverse scenario with either blocklist or link. ~Probably blocklist is simpler in this case~ Link will be the most consistent option (although either could work), but you'll need to also include a function to handle this more complex type of condition:
> 
> Here's an example that will unfade everything when 'NERDTree' is focused -- for the `main` window part I'm guessing you may want some additional logic before returning `True`.
> 
> ```python
> python3 << EOF 
> from vimade import vimade
> def link_when_nerdtree_opened(win, active):
>  # active is the window that vimade considers 'focused' ... it can be `None` at times
>   if active and 'NERDTree' in active.buf_vars:
>     return True
>   return False
> vimade.setup(
>   # ... other options
>   link = {
>     'link_when_nerdtree_opened': link_when_nerdtree_opened,
>     # ... other link rules
>   }
> )
> EOF
> ```



Thx, and one more question, how can I access access `filetype` of `buf_opts` from python properly? (`active.buf_opts.filetype` doesn't work)

I'm trying to get it works based on your code but it fails for undotree ( check `b:UndotreeBuffer` is not working great).

```
def nofade_intree(win, active):
	if active and any(key in active.buf_vars for key in ['NERDTree', 'UndotreeBuffer']):
		return True
	return False

vimade.setup(
	recipe = ['minimalist', {'animate': True}],
	link = {
		'test': nofade_intree,
	}
)
```

**Comment by TaDaa** [comment]
for the undotree above you could use `isUndotreeBuffer` if you want to continue using the vars approach.

For switching to filetype you access it like this (note that `str(..., 'utf8')` may or may not be required, vim is inconsistent on some systems for whether or not it returns a byte string or string):

```
python3 << EOF
def nofade_intree(win, active):
  if (active and str(active.buf_opts['filetype'], 'utf8') in ('nerdtree','undotree')):
    return True
  return False

vimade.setup(
	recipe = ['minimalist', {'animate': True}],
	link = {
		'test': nofade_intree,
	}
)
EOF

```

**Comment by toooonyy** [comment]
Thanks a lot, all good right now.

For future search, here's what I'm using(on arm macOS with vim 9.1). All windows won't fade when you're in nerdtree, undotree+diff window
my vimade config
```python
function! SetupMyVimadeConfig()
python3 << EOF
from vimade import vimade
from vimade.recipe.minimalist import Minimalist

def nofade_intree(win, active):
	if (active and str(active.buf_opts['filetype'], 'utf8') in ('nerdtree', 'undotree', 'diff')):
		return True
	return False

vimade.setup(
	recipe = ['minimalist', {'animate': True}],
	link = {
		'test': nofade_intree,
	}
)
EOF
endfunction

au! User Vimade#PythonReady call SetupMyVimadeConfig()

let g:vimade = {}
let g:vimade.lazy = 1

autocmd WinEnter * ++once call vimade#Load()

```
