### ISSUE TITLE
fade the terminal windows....

### ISSUE THREAD

**Issue by Nirajgns** [TaDaa/vimade#87]

**Comment by TaDaa** [comment]
Thanks for filing @Nirajgns !

We should be able to add partial support for terminals, that is make it behave like the Python version of Vimade.  This means all highlights will be faded to `Normal` except for ones with real highlight colors.

We can't fully add support for all terminal colors b/c Neovim+Vim use special highlights in terminals such as `g:terminal_color_1`, `g:terminal_color_2`, etc..  These special colors don't have real highlight groups and can't be changed on the fly.

An alternative solution is to use a floating window with `winblend` on terminal windows, which does fade these special groups as expected **BUT** it comes with many other issues that makes it not a good approach.  Issues include:
-  loss of transparency (Neovim forces a black background)
- strange underline behaviors in some scenarios
- colors are completely incorrect on 256 colors (`set notermguicolors`)
- inconsistent with other behaviors in Vimade (i.e tinting, etc)

Likely implementation:
- Toggle terminals when `nc=true` add matchall (`matchadd('Normal','.*')`)
- Remove blocklist default

----
I think this should be a pretty simple approach, maybe I can put it in this weekend

**Comment by TaDaa** [comment]
Should be all set (until Neovim adds proper highlight groups for terminal colors:D).  LMK if that ends up working out for you

**Comment by TaDaa** [comment]
Closing this out, but feel free to re-open or file a new issue if you run into any troubles.  Thanks for filing!
