### ISSUE TITLE
[Bug] Telescope highlights on version 2.1.1

### ISSUE THREAD

**Issue by mrmerc** [TaDaa/vimade#88]
Plugin resets my Telescope border to the Normal highlights on version 2.1.1

Version 2.1.0

![Снимок экрана 2024-12-28 в 01 19 14](https://github.com/user-attachments/assets/150134d7-7dff-4bb4-b7a2-861943e00d90)

Version 2.1.1

![Снимок экрана 2024-12-28 в 01 18 32](https://github.com/user-attachments/assets/4a3bb161-1f5d-4271-82a8-aae23ac0968b)

**Comment by TaDaa** [comment]
Thanks for reporting and finding the broken revision @mrmerc !  Should be resolved,  the curse of saying something should be a no-op for users 😿

**Comment by mrmerc** [comment]
Resolved indeed. Gonna continue enjoying your plugin. Thank you!
