### ISSUE TITLE
It works, but complaining about "could not load colors" on start up

### ISSUE THREAD

**Issue by yifeikong** [TaDaa/vimade#9]
In vim 8.0, tmux 2.8 and ubuntu 18.04. Vimade works, but complains "Vimade: could not load colors, make sure you either use a colorscheme that defines a background and foreground for 'Normal' or configure g:vimade.basefg and g:vimade.basebg" when starting up.

VimadeInfo is 

```
{"version":"0.0.1","python":{"BACKGROUND":"dark","BASE_FG":[208,208,208],"BASE_FG_LAST":"252","BASE_BG_EXP":"233","BASE_HI":[[208,208,208],[18,18,18]],"COLORSCHEME":"\nmolokai","HI_FG":" ctermfg=","ORIGINAL_BACKGROUND":"dark","BASE_BG":[18,18,18],"COL_BUF_SIZE":30,"IS_NVI
M":0,"TERM_BG":"#000000","ROW_BUF_SIZE":30,"BASE_BG_LAST":"233","NORMAL_ID":"86","TERMGUICOLORS":0,"BASE_FADE":"59","FADE_LEVEL":0.4,"TERM_FG":"#FFFFFF","IS_TERM":1,"IS_TMUX":0,"BASE_FG_EXP":"252","HI_BG":" ctermbg="},"other":{"background":"dark","normal_hi":["252","233"]
,"vimade_py_cmd":"py3","has_gui":0,"has_python":0,"vimade_timer":14089,"has_gui_running":0,"syntax":"","has_nvim":0,"normal_id":86,"vimade_running":1,"colorscheme":"\nmolokai","vimade_loaded":1,"vimade_usecursorhold":0,"has_python3":1},"config":{"basebg":"","basefg":"","f
adelevel":0.4,"rowbufsize":30,"colbufsize":30,"normalid":86,"checkinterval":32}}
```

**Comment by Herz3h** [comment]
I have the same issue after updating the plugin today. I use VIM 8.1 in tmux 2.6. I commented line 124 in [this file](https://github.com/TaDaa/vimade/blame/0ff227876635786a306edc1b1c4cfbb54fbf460e/lib/vimade.py#L92)

**Comment by TaDaa** [comment]
Should be fixed on latest, let me know if you still see issues.  Tmux support should be better as well (detects tmux background/foreground) on supported terminals (gnome, kitty, tilix atm)

**Comment by yifeikong** [comment]
Thanks for the fix!
